const mobileData = [
  {
    id: 0,
    title: "Huawei 3i",
    price: 750,
    desc: "Huawei nova 3i has 3 personality color options: Pearl White, Black and Infrared Purple. With a solid metal frame, glossy glass back and special paint, Huawei nova 3i is beautiful. The device has a modern, neat design that fits in a pocket but still carries a large screen. You will enjoy everything in a big way through Huawei nova 3i's 6.3-inch Full HD+ screen",
    img: "https://fptshop.com.vn/Uploads/images/2015/Tin-Tuc/QuanLNH2/huawei-nova-3i-mo-ta-1.jpg",
    type: "mobile",
  },
  {
    id: 1,
    title: "IPhone 8",
    price: 800,
    desc: "Lower brightness does conserve battery life but dark mode on a LCD screen does NOT improve battery life. All pixels are active, there is no true black (inactive pixels) like on LED screens. I'm surprised so many people here don't know this..",
    img: "https://cdn.tgdd.vn/Products/Images/42/114113/iphone-8-64gb-hh-600x600.jpg",
    type: "mobile",
  },
  {
    id: 2,
    title: "IPhone 12 Mini",
    price: 950,
    desc: "O Samsung Ocean é uma iniciativa da Samsung no Brasil que oferece capacitação tecnológica à comunidade e fomenta a criação de empresas de base tecnológica (startups). Com instalações modernas, o programa oferece gratuitamente treinamentos técnicos combinados com temas relacionados à usabilidade e ao empreendedorismo, além do contato com especialistas da empresa e do mercado.",
    img: "https://cdn.hoanghamobile.com/i/preview/Uploads/2020/11/06/apple-iphone-12-mini-3.png",
    type: "mobile",
  },
  {
    id: 3,
    title: "Samsung Ocean 12",
    price: 1050,
    desc: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
    img: "https://anhducdigital.vn/media/product/5514_samsung_galaxy_note_9_chinh_hang_blue.jpg",
    type: "mobile",
  },
  {
    id: 4,
    title: "Huawei 40 mate Pro",
    price: 1150,
    desc: "At first glance, the iPhone 12 Pro looks like a phone that's caught between two stools. With the same dimensions and chipset as the iPhone 12, it’s easy to wonder whether the Pro is worth the extra cash – especially when the iPhone 12 Pro Max is out there with a better camera sensor and longer battery life. There are some useful upgrades here – not least the camera, and the jump to 128GB of storage in the cheapest model, and it also comes in more muted, premium-looking colors. It's the more mature iPhone for sure – but it's tough to say it's got enough to encourage you to upgrade.",
    img: "https://cdn.tgdd.vn/Products/Images/42/226253/huawei-mate-40-pro-600jpg-600x600.jpg",
    type: "mobile",
  },
  {
    id: 5,
    title: "IPhone 12 Pro Max",
    price: 2000,
    desc: "At first glance, the iPhone 12 Pro looks like a phone that's caught between two stools. With the same dimensions and chipset as the iPhone 12, it’s easy to wonder whether the Pro is worth the extra cash – especially when the iPhone 12 Pro Max is out there with a better camera sensor and longer battery life. There are some useful upgrades here – not least the camera, and the jump to 128GB of storage in the cheapest model, and it also comes in more muted, premium-looking colors. It's the more mature iPhone for sure – but it's tough to say it's got enough to encourage you to upgrade.",
    img: "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-xam-new-600x600-200x200.jpg",
    type: "mobile",
  },
  {
    id: 6,
    title: "Huawei Nova 9",
    price: 1200,
    desc: "The Nova 9 has a battery capacity of 4,300mAh and supports 66W fast charging while the Nova 9 Pro has a smaller capacity battery of only 4,000mAh but charges faster at 100W. Huawei claims its smartphone will fully charge the battery in just 20 minutes. Particularly, the Pro version integrates VC + graphene cooling technology to reduce temperatures when playing games or running CPU-intensive tasks..",
    img: "https://vnmedia.vn/file/8a10a0d36ccebc89016ce0c6fa3e1b83/8a10a0d36d961641016da40a3b750829/092021/huawei_nova_9_pro_20210923221941.jpg",
    type: "mobile",
  },
  {
    id: 7,
    title: "Samsung Galaxy A02",
    price: 300,
    desc: "Galaxy A02 uses typical plastic materials with eye-catching youthful colors, providing a lightweight, comfortable device for you to hold or carry, convenient in daily operation..",
    img: "https://cdn.tgdd.vn/Products/Images/42/228999/samsung-galaxy-a02-den-600x600-200x200.jpg",
    type: "mobile",
  },
  {
    id: 8,
    title: "Samsung Galaxy FlipZ",
    price: 300,
    desc: "Samsung Galaxy Z Flip owns a breakthrough design like a chalk box, with a 6.7-inch main screen, 1.1-inch small screen, High-end performance with Snapdragon 855 chip, is the flagship suitable for users high class, high class.",
    img: "https://didongviet.vn/pub/media/catalog/product//g/a/galaxy-x-flip-didongviet.jpg",
    type: "mobile",
  },
  {
    id: 9,
    title: "IPhone 10",
    price: 2000,
    desc: "iPhone X uses OLED panels (refined by Apple) instead of LCD like previous iPhones and this gives the device a very deep black color and equally accurate color reproduction.",
    img: "https://cdn.tgdd.vn/Products/Images/42/114115/iphone-x-64gb-bac-org.png",
    type: "mobile",
  },
  {
    id: 10,
    title: "Headphone DAREU",
    price: 200,
    desc: "In fact, this is the most easily encountered headphone design in everyday life because they have the most compact size, do not include a headband and are often included in a smartphone case. This product line is divided into two different designs, Earbuds and In-ears. While the Earbud's audio driver can only be installed simply outside the ear cavity, the In-ear is designed to bring the audio driver deeper into the ear canal and soundproof thanks to the rubber stopper. Actual experience shows that the sound quality that In-ear headphones perform is often better than Earbuds.",
    img: "https://images.fpt.shop/unsafe/filters:quality(90)/fptshop.com.vn/uploads/images/tin-tuc/120176/Originals/Headphone-la-gi-co-may-loai-thiet-ke-cua-headphone-4.jpg",
    type: "accesory",
  },
  {
    id: 11,
    title: "Huawei Earphone",
    price: 200,
    desc: "The Huawei FreeBuds Lite want to score top marks by delivering an ultimate experience thanks to True Wireless technology, impressive sound and an ingenious dual microphone design with integrated noise reduction capabilities for enhanced communications over the phone. Or at least they claim so in their advertising campaigns",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxhBmur_xul9c3fCAUpWLpDX5IltkHpfp6fOzaWlNTpNZRV37M-SQqo3HiuM0otLByKY8&usqp=CAU",
    type: "accesory",
  },
  {
    id: 12,
    title: "Power Slim",
    price: 200,
    desc: "Ultra-Compact: Smallest and Lightest design more convenient to carry, you can easily slip it in your bag or pocket.Pocket-sized design, convenient to carry with on the way High Capacity: 5000 mAh, rated output about 3300mAh(5000mah*3.7V/5V*90%). Enough to provide two charges to an iPhone 6s. Please be fully charged for the first time Upgraded Charging Technology: Auto detect your device and deliver its fully-intended charge speed up to 2.1A at most once connected (by using an adapter with 2 amps output)",
    img: "https://m.media-amazon.com/images/I/61++SPxRHbL._AC_SL1500_.jpg",
    type: "accesory",
  },
  {
    id: 13,
    title: "Apple Ipad 12",
    price: 2200,
    desc: "Find out the Apple iPad 32GB 10.2´´ Tablet in stock and at the best price. Also have a look on our Tablets-ereaders sales and choose our best offers. Find the latest reductions and discover all our sales on Tablets products at amazing discount prices! All this to ensure you get the cheapest deal every time at techinn.",
    img: "https://www.techinn.com/f/13777/137777408/apple-ipad-32gb-10.2-tablet.jpg",
    type: "tablet",
  },
  {
    id: 14,
    title: "LenovoTab Plus",
    price: 3200,
    desc: "Lenovo Tab M10 - FHD Plus is fully protected by a solid metal frame, slightly square, curved, and shiny edges. The tablet has a trendy modern look in a simple yet attractive design.",
    img: "https://cdn.tgdd.vn/Products/Images/522/244684/lenovo-tab-p11-plus-2-600x600.jpg",
    type: "tablet",
  },
  {
    id: 15,
    title: "Samsung Tab S7",
    price: 1220,
    desc: "With the ultra-thin, lightweight, portable design of a top-end premium tablet, the Samsung Galaxy Tab S7 Wifi T870 Tablet also carries the power of a desktop computer with excellent configuration. The Snapdragon 865+ processor is manufactured on the 7nm+ process, with 8 cores clocked at up to 3.09 GHz with the super-powerful Adreno 650 graphics GPU, making every task smooth.",
    img: "https://cdn.tgdd.vn/Products/Images/522/228144/samsung-galaxy-tab-a7-2020-vangdong-200x200.jpg",
    type: "tablet",
  },
];

export default mobileData;
